# permissions for end users to view architects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: architect-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: matrix-operator2
    app.kubernetes.io/part-of: matrix-operator2
    app.kubernetes.io/managed-by: kustomize
  name: architect-viewer-role
rules:
- apiGroups:
  - matrix.operator.com
  resources:
  - architects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - matrix.operator.com
  resources:
  - architects/status
  verbs:
  - get
