# permissions for end users to edit merovingians.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: merovingian-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: matrix-operator2
    app.kubernetes.io/part-of: matrix-operator2
    app.kubernetes.io/managed-by: kustomize
  name: merovingian-editor-role
rules:
- apiGroups:
  - matrix.operator.com
  resources:
  - merovingians
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matrix.operator.com
  resources:
  - merovingians/status
  verbs:
  - get
