---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - namespaces
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matrix.operator.com
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matrix.operator.com
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - architects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matrix.operator.com
  resources:
  - architects/finalizers
  verbs:
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - architects/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - merovingians
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matrix.operator.com
  resources:
  - merovingians/finalizers
  verbs:
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - merovingians/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - oracles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matrix.operator.com
  resources:
  - oracles/finalizers
  verbs:
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - oracles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - twins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - matrix.operator.com
  resources:
  - twins/finalizers
  verbs:
  - update
- apiGroups:
  - matrix.operator.com
  resources:
  - twins/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
