## Append samples you want in your CSV to this file as resources ##
resources:
- matrix.operator.com_v1alpha1_agent.yaml
- matrix.operator.com_v1alpha1_architect.yaml
- matrix.operator.com_v1alpha1_oracle.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
